# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build-and-deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.15.1'
    - run: npm ci
    - run: npm run build
    - run: npm test

  e2e-tests:
    needs: [build]
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    steps:
      - uses: microsoft/playwright-github-action@v1
      - name: Run E2E tests
        run: npm run test:integration
      
